### ISSUE TITLE
Offshore Wind Debt Fraction Calculator throwing error

### ISSUE THREAD

**Issue by NoahV-SC** [NREL/ATB-calc#21]
I'm receiving an error when calculating new debt fractions for offshore wind (both fixed and floating).
I am able to run debt fractions for other technologies (land-based wind, and utility PV) without issue, but when I attempt to run the debt fraction processor for all technologies or just for offshore wind, I receive a key error.

  File "<PATH>pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'Fixed-Bottom Offshore Wind'`

(running Python 3.11.9)

**Comment by brtietz** [comment]
@NoahV-SC Thanks for reporting! I have a proposed fix here https://github.com/NREL/ATB-calc/pull/22 - mind testing and letting us know how it goes?

**Comment by NoahV-SC** [comment]
Thanks Brian! That seems to work for Fixed Offshore Wind, but there still seem to be problems with Floating OSW: 

Loading data from Floating Offshore Wind, for R&D and 20
        Loading metrics
        Loading assumptions
        Loading WACC data
        Done loading data
Traceback (most recent call last):
  File "C:\Users\noah.verbeek\anaconda3\Lib\site-packages\pandas\core\internals\construction.py", line 939, in _finalize_columns_and_data
    columns = _validate_or_indexify_columns(contents, columns)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\noah.verbeek\anaconda3\Lib\site-packages\pandas\core\internals\construction.py", line 986, in _validate_or_indexify_columns
    raise AssertionError(
AssertionError: 31 columns passed, passed data had 23 columns

**Comment by brtietz** [comment]
Thanks for testing! I am not able to reproduce that error - can you share the version of the ATB spreadsheet you're running with (if it varies from the version at https://atb.nrel.gov/electricity/2024/data)

The error there suggests something about a difference in the base year - given that fixed starts in 2022 and floating starts in 2030 if that helps you debug.

**Comment by mikebannis** [comment]
Noah, we're looking into this and I think we have an answer. Testing it out now. Hopefully will have everything working after the weekend.
